stages:
- build

build:
  stage: build
  tags:
   - shared
   - shell
  variables:
    VAULT_ADDR: https://vault.mercurylark.corp:8200
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.mercurylark.corp:8200
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=dev-projects jwt=${VAULT_ID_TOKEN})"
    - echo $VAULT_TOKEN | base64
