stages:
  - deploy

deploy:
  stage: deploy
  variables:
    VAULT_ADDR: https://vault.mercurylark.corp:8200
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.mercurylark.corp:8200
  tags:
    - shared
    - shell 
  before_script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=dev-projects jwt=${VAULT_ID_TOKEN})"
    - export KUBE_CONFIG="$(vault kv get -field=config secret/dev/k8s)"
    - mkdir ~/.kube
    - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
  script:
    - echo "Deploying the application... nginx"
    - kubectl apply -f deployment.yaml --namespace=dev --validate=false
  after_script:
    - rm -rf ~/.kube
