apiVersion: v1
kind: Pod
metadata:
  name: test-balancer-for-ml-app
  namespace: dev

spec:
  containers:
    - name: nginx
      image: harbor.mercurylark.corp/dev/nginx:latest 
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: harbor-secret-dev
