apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlbalancer-test-feature
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbalancer-test-feature
  template:
    metadata:
      labels:
        app: mlbalancer-test-feature
    spec:
      serviceAccountName: dev-pod-creator
      containers:
      - name: mlbalancer-test-feature
        image: harbor.mercurylark.corp/dev/ubunru:latest
      imagePullSecrets:
      - name: harbor-secret-dev