apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: harbor.mercurylark.corp/dev/nginx:latest 
        ports:
        - containerPort: 80
